language: python

python:
  - '3.6'

branches:
  only:
    - master

services:
  - docker

before_install:
  - make travis_up

install:
  - pip install -r requirements/travis.txt

script:
  - make travis_test
  - make travis_pii_check
  - make docker_build

after_success:
  - pip install -U codecov
  - docker exec notes /edx/app/notes/notes/.travis/run_coverage.sh
  - codecov

jobs:
  include:
    - name: Django 1.11
      env:
      - TOXENV=django111
    - name: Django 2.0
      env:
      - TOXENV=django20
    - name: Django 2.1
      env:
      - TOXENV=django21
    - name: Django 2.2
      env:
      - TOXENV=django22
    - name: Docker Build
      before_install: []
      install: []
      script:
        - make docker_build

env:
  global:
    - DOCKER_USERNAME=edxbuilder
    # encrypted DOCKER_PASSWORD
    - secure: OgsQf8hp40s+E2btyl+RHcdgjqx9gZ4phlvm2tQ8Oy9mCO6hAy2XCjL1m2bidaFzwSjZXDZ7BhjD3yXpW2B+zP/yJNVKmdPA5E+D7YgFPdlOv7Wb+t0Z083Wbwqk7ZZgxLCcMLWf5vTs/QkPVAXbU8wJvQQC2l0EKESFnYkzNAI=

deploy:
  provider: script
  script: make travis_docker_push
  on:
    branch: master
